services:
  - name: my-flask-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python your_flask_app.py
    envVars:
      - key: FLASK_ENV
        value: production
