services:
  - name: my-flask-api
    type: web
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
